### ISSUE TITLE
It's malware 

### ISSUE THREAD

**Issue by squirticulous** [w-shackleton/android-netspoof#212]
My Norton security by Symantec says it's malware don't download

**Comment by w-shackleton** [comment]
You're downloading an app that interferes with a network - this is why they
are reporting it as malicious; it can be used as such.

**Comment by Jack-Rickwood** [comment]
@w-shackleton Sorry to bother you, but after setting the custom root path to /sbin/su it detects root fine, but the app still wont work! I just get this error: "Unable to retrieve local hardware address libnet ( ioctl: Permission Denied )." Is this just because the app is outdated, or my phone (sm-g930f) is not supported? Is there any way i can fix this?
